[project]
name = "caspoon"
version = "0.1.0"
description = "Caspoon Reverse Engineering Toolkit"
authors = [
  { name = "LosEvons" }
]
requires-python = ">=3.10"

dependencies = [
  "textual",
  "pyelftools",
  "r2pipe",
  "rich"
]

[project.scripts]
caspoon = "caspoon.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
