[metadata]
name = caspoon
version = 0.1.0
description = Caspoon Reverse Engineering Toolkit

[options]
packages =
    caspoon
    caspoon.ui
    caspoon.core
    caspoon.recon
    caspoon.backends
python_requires = >=3.10
install_requires =
    textual
    pyelftools
    r2pipe
    rich

package_dir =
    caspoon = .
